module.exports = {
  extends: [
    'stylelint-prettier/recommended',
    'stylelint-config-recess-order',
    'stylelint-config-standard-scss',
  ],
  plugins: ['stylelint-prettier'],
  rules: {
    'prettier/prettier': true,
    'string-quotes': 'single',
    'color-no-invalid-hex': true,
    'color-function-notation': 'legacy',
    'font-family-no-duplicate-names': true,
    'font-family-name-quotes': 'always-unless-keyword',
    'selector-class-pattern': '^[a-zA-Z][a-zA-Z0-9]+$',
    'selector-pseudo-element-colon-notation': 'single',
    'function-calc-no-unspaced-operator': true,
    'unit-no-unknown': true,
    'property-no-unknown': [true, { severity: 'warning' }],
    'block-no-empty': true,
    'no-duplicate-at-import-rules': true,
    'no-extra-semicolons': true,
    'no-invalid-double-slash-comments': true,
    'block-closing-brace-newline-after': 'always',
    'declaration-block-no-shorthand-property-overrides': [
      true,
      { severity: 'warning' },
    ],
  },
};
